### ISSUE TITLE
OverwatchArcade.Today - breaking API

### ISSUE THREAD

**Issue by Quintenps** [NiGhTTraX/isitmayhem#2]
Hey Nighttrax,

A while ago I told you about a new version of OverwatchArcade.Today.
The new version has API breaking changes so just wanted to let you know.

We will most likely launch the new website on the 24th, that'll give developers some time to refactor to the new API.
There is a beta/testing version available at https://beta.overwatcharcade.today, you can find and test the API there.

Thanks :)

**Comment by NiGhTTraX** [comment]
Hey @Quintenps, thanks for the heads up. Will the upcoming release remove the existing API? I've prepared #3 to migrate to the new version.

**Comment by Quintenps** [comment]
Yep, it'll be replaced
